### ISSUE TITLE
ld crashes while linking LaunchAPPLServer for PowerPC

### ISSUE THREAD

**Issue by autc04** [autc04/Retro68#69]
This happens on both my current Mac and my vintage G5, but not on Linux.

```
Scanning dependencies of target LaunchAPPLServer
[ 80%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/LaunchAPPLServer.cc.obj
[ 81%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/AppLauncher.cc.obj
[ 82%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/ToolLauncher.cc.obj
[ 84%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/StatusDisplay.cc.obj
[ 85%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/AboutBox.cc.obj
[ 86%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/SerialConnectionProvider.cc.obj
[ 88%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/MacSerialStream.cc.obj
[ 89%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/MacTCPStream.cc.obj
[ 90%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/TCPConnectionProvider.cc.obj
[ 92%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/OpenTptStream.cc.obj
[ 93%] Building CXX object LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/OpenTptConnectionProvider.cc.obj
[ 94%] Linking CXX executable LaunchAPPLServer.xcoff
collect2: fatal error: ld terminated with signal 11 [Segmentation fault: 11], core dumped
compilation terminated.
make[2]: *** [LaunchAPPL/Server/LaunchAPPLServer.xcoff] Error 1
make[2]: *** Deleting file `LaunchAPPL/Server/LaunchAPPLServer.xcoff'
make[1]: *** [LaunchAPPL/Server/CMakeFiles/LaunchAPPLServer.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by simonboak** [comment]
Exact same error here, macOS 10.14 with fresh install of Retro68 and dependancies.

**Comment by autc04** [comment]
To the best of my knowledge, this is fixed now.

I have opened an upstream ticket for binutils: https://sourceware.org/bugzilla/show_bug.cgi?id=24055

**Comment by TheFakeMontyOnTheRun** [comment]
Oddly enough, I'm still getting this on Monterrey (x86_64) :(
But built fine on my Ubuntu Thinkpad.
